// ES6 module syntax
import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

let strings = new LocalizedStrings({
 en:{
   loginEmailLabel:"Type your e-mail.",
   loginPasswordLabel:"Type your password.",
   noAccount:"Don't have an account?",
   registerNow:"Register now!",
   buttonEnter:"Enter",
   registerName:"",
   registerNameLabel:"",
   registerEmail:"",
   registerEmailLabel:"",
   registerPassword:"",
   registerPasswordLabel:"",
   registerButton:"",
   hasAccount:"",
   logNow:"",
   group:"",
   createGroup:"",
   createBag:"",
   about:"",
   logoff:"",
   typeGroupName:"",
   selectBag:"",
   selectCoin:"",
   real:"",
   dolar:"",
   euro:"",
   libra:"",
   buttonCreate:"" ,
   typeBagName:"",
   selectCoinAndAmount:"",
   whoWeAre:"",
   textAbout:"",
   developerFront:"",
   uxDesign: "",
   developerBack:"",
   historc:"",
   financialMovement:"",
   save:"",
   cancel:""
 },
 pt: {
  loginEmailLabel:"Digite seu email.",
  loginPasswordLabel:"Digite sua senha.",
  noAccount:"Não possui uma conta?",
  registerNow:"Registre-se!",
  buttonEnter:"Entrar",
  registerName:"",
  registerNameLabel:"",
  registerEmail:"",
  registerEmailLabel:"",
  registerPassword:"",
  registerPasswordLabel:"",
  registerButton:"",
  hasAccount:"",
  logNow:"",
  group:"",
  createGroup:"",
  createBag:"",
  about:"",
  logoff:"",
  typeGroupName:"",
  selectBag:"",
  selectCoin:"",
  real:"",
  dolar:"",
  euro:"",
  libra:"",
  buttonCreate:"" ,
  typeBagName:"",
  selectCoinAndAmount:"",
  whoWeAre:"",
  textAbout:"",
  developerFront:"",
  uxDesign: "",
  developerBack:"",
  historc:"",
  financialMovement:"",
  save:"",
  cancel:""
 }
});


export default strings;