// ES6 module syntax
import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings  = require ('react-native-localization');

let strings = new LocalizedStrings({
 en:{
   loginEmailLabel:"Type your e-mail.",
   loginPasswordLabel:"Type your password.",
   noAccount:"Don't have an account?",
   registerNow:"Register now!",
   buttonEnter:"Enter",
   registerName:"Name",
   registerNameLabel:"Type here your name.",
   registerEmail:"Email",
   registerEmailLabel:"Type here your email.",
   registerPassword:"Password",
   registerPasswordLabel:"Type here your password.",
   registerButton:"Register",
   hasAccount:"Already has an account?",
   logNow:"Log in",
   group:"Groups",
   createGroup:"Create Group",
   createBag:"Create Bag",
   about:"About us",
   logoff:"Sign Out",
   typeGroupName:"Type the group's name:",
   selectBag:"the bags for the group:",
   selectCoin:"the currency",
   real:"Brazilian Real",
   dolar:"Dolar",
   euro:"Euro",
   libra:"Pound",
   buttonCreate:"CREATE" ,
   typeBagName:"Type the bag's name",
   selectCoinAndAmount:"Select the currency's type/",
   typeQuantity:"Type the Quantity:",
   select:"Select",
   whoWeAre:"About us",
   textAbout:"Our team is composed of Bachelor's Degree students in Computer Science at Universidade Federal Rural de Pernambuco (UFRPE) mainly in the following roles, but not limited to them:",
   developerFront:"Front-End Developer",
   uxDesign: "Ux Designer",
   developerBack:"Back-End Developer",
   historc:"History",
   financialMovement:"Financial Movement",
   save:"SAVE",
   cancel:"CANCEL"
 },
 pt: {
  loginEmailLabel:"Digite seu email.",
  loginPasswordLabel:"Digite sua senha.",
  noAccount:"Não possui uma conta?",
  registerNow:"Registre-se!",
  buttonEnter:"Entrar",
  registerName:"Nome",
  registerNameLabel:"Digite seu nome.",
  registerEmail:"Email",
  registerEmailLabel:"Digite seu email.",
  registerPassword:"Senha",
  registerPasswordLabel:"Digite sua senha.",
  registerButton:"Registrar-se",
  hasAccount:"Já possui uma conta?",
  logNow:"Faça Login!",
  group:"Grupos",
  createGroup:"Criar Grupo",
  createBag:"Criar Maleta",
  about:"Sobre",
  logoff:"Sair",
  typeGroupName:"Digite o nome do Grupo:",
  selectBag:"as Maletas do Grupo:",
  selectCoin:"Selecione a Moeda",
  real:"Real Brasileiro",
  dolar:"Dólar Americano",
  euro:"Euro",
  libra:"Libra Esterlina",
  buttonCreate:"CRIAR" ,
  typeBagName:"Digite o nome da Maleta:",
  select:"Selecione",
  selectCoinAndAmount:"Selecione o tipo da Moeda/",
  typeQuantity:"Digite a Quantidade:",
  whoWeAre:"Quem Somos?",
  textAbout:"Nossa equipe é composta por estudantes de Bacharelado em Ciência da Computação na Universidade Federal Rural de Pernambuco (UFRPE) atuando principalmente nas seguintes funções, mas não se limitando a elas:",
  developerFront:"Desenvolvedor Front-End",
  uxDesign: "UX Designer",
  developerBack:"Desenvolvedor Back-End",
  historc:"Histórico",
  financialMovement:"Movimentação Financeira",
  save:"SALVAR",
  cancel:"CANCELAR"
 }
});


export default strings;